apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: production
spec:
  selector:
    app: rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer