version: 0.2

env:
  variables:
    NODE_ENV: "${environment}"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  pre_build:
    commands:
      - npm i
      - npm run test
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  name: "artifact-${environment}"
  base-directory: build